"""Backwards-compat shim.

The 1,500+ line monolith was split into `uganda_compliance.efris.services.sales_invoice`
in PR 3 (Phase 4 of the refactor plan). Existing imports and `hooks.py`
`doc_events` paths continue to work because every public symbol is re-exported
here under its original name.

For new code, prefer `from uganda_compliance.efris.services.sales_invoice import ...`
or import from the focused submodule directly.
"""
from uganda_compliance.efris.services.sales_invoice import (  # noqa: F401
    EInvoiceAPI,
    Sales_invoice_is_efris_validation,
    _calculate_tax_adjustments,
    _check_efris_items,
    _handle_efris_logic,
    _handle_sales_invoice,
    _handle_sales_return,
    _parse_doc,
    _process_items,
    _set_sales_taxes_template,
    _update_row_values,
    _validate_item_uom,
    after_save_sales_invoice,
    before_save,
    calculate_additional_discounts,
    cancel_irn,
    check_credit_note_approval_status,
    check_efris_flag_for_sales_invoice,
    confirm_irn_cancellation,
    create_buyer_details,
    create_credit_note,
    create_e_invoice,
    create_goods_details,
    create_payment_details,
    create_summary,
    create_tax_details,
    decode_e_tax_rate,
    fetch_fdn_details,
    generate_irn,
    get_basic_information,
    get_buyer_details,
    get_credit_note_reason,
    get_efris_product_code,
    get_einvoice,
    get_goods_details,
    get_import_service_seller,
    get_order_no,
    get_original_invoice_details,
    get_payment_details,
    get_summary_details,
    get_tax_details,
    handle_approved_credit_note,
    handle_rejected_credit_note,
    initialize_credit_note,
    negate_credit_note_values,
    new_credit_note_rate,
    notify_system_managers,
    on_cancel_sales_invoice,
    on_submit_sales_invoice,
    on_update_sales_invoice,
    sales_uom_validation,
    send_einvoice_to_efris,
    send_to_efris,
    set_efris_based_on_items,
    update_einvoice_with_fdn_details,
    update_original_invoice_status,
    update_sales_invoice_return_status,
    validate_company,
    validate_efris_warehouse,
    validate_payment,
    validate_sales_invoice,
)
